import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/context/SessionContext";

import ToastContainer from "@/components/providers/toast/ToastContainer";
import Navbar from "@/components/ui/nav/Navbar";
import { getUserFromCookie } from "@/utils/session";
import { SiteSettingsProvider } from "@/context/SiteSettingsContext";
import { getSiteSettings } from "@/lib/payloadcms/payloadcms";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookie();
  const settings = await getSiteSettings();

  return (
    <html lang="en">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SiteSettingsProvider value={null}>
          <SessionProvider>
            <Navbar navigationBar={settings.navigationBar} userLoggedIn={!!user} />
            {children}

            <ToastContainer />
          </SessionProvider>
        </SiteSettingsProvider>
      </body>
    </html>
  );
}
